language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
script: bundle exec rspec
before_install:
  # fixes Travis CI error: NoMethodError: undefined method `spec' for nil:NilClass
  - gem install bundler
gemfile:
  - gemfiles/rack-1.3.gemfile
  - gemfiles/rack-2.0.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rack-2.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rack-2.0.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/rack-2.0.gemfile
